### ISSUE TITLE
Playground doesn't work with Safari

### ISSUE THREAD

**Issue by bowsersenior** [cue-sh/playground#12]
Using Safari on Mac, I get the following error:

```
TypeError: WebAssembly.instantiateStreaming is not a function. (In 'WebAssembly.instantiateStreaming(fetch("main.wasm"),a.importObject)', 'WebAssembly.instantiateStreaming' is undefined)
```

<img width="1442" alt="Screen Shot 2021-04-05 at 11 13 24 AM" src="https://user-images.githubusercontent.com/40264/113590400-99d56e80-9600-11eb-8056-cbdd98c4e8fd.png">

This seems to be caused by lack of support in Safari for `WebAssembly.instantiateStreaming` per [Mozilla docs](https://developer.mozilla.org/en-US/docs/WebAssembly).

One solution would be to check if `WebAssembly.instantiateStreaming` is defined, and if not, fall back to [WebAssembly.instantiate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate), which is supported by Safari, in [index.tsx](https://github.com/cue-sh/playground/blob/a768b6e5aed0a45438487493919a943af7fa57ad/src/index.tsx#L39).

**Comment by myitcv** [comment]
Thanks for flagging this @bowsersenior 

We'd certainly appreciate anyone who might be interested in submitting a PR to fix this.

**Comment by bowsersenior** [comment]
Hi @myitcv , I just checked https://cuelang.org/play today and the issue is still there. Perhaps a new deployment is needed?

**Comment by myitcv** [comment]
Thanks for the reminder, @bowsersenior - this also needs a release over at https://github.com/cuelang/cuelang.org. I'm doing that now.

**Comment by myitcv** [comment]
(and I'm putting in place something that will ensure we are reminded to upgrade to the latest playground/`cuelang.org/go` modules)

**Comment by bowsersenior** [comment]
Awesome, thanks!

**Comment by myitcv** [comment]
Should be fixed now: https://cuelang.org/play/#cue@export@cue
